local SignInCfg = {}

SignInCfg.Cfg = {
    {day = 1,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 2,propname = "超级加倍",propnum = 3,propid = 33,imgpath = "img_double_ddzyh.png"},
    {day = 3,propname = "绿宝石",propnum = 5,propid = 10,imgpath = "img_diamond_forge_ddzyh.png"},
    {day = 4,propname = "金豆",propnum = 2000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 5,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 6,propname = "金豆",propnum = 2000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 7,propname = "蓝宝石",propnum = 5,propid = 11,imgpath = "img_diamond3_forge_ddzyh.png"},
    {day = 8,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 9,propname = "钻石",propnum = 3,propid = 2,imgpath = "shop_diamond2_ddzyh.png"},
    {day = 10,propname = "金豆",propnum = 3000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 11,propname = "金豆",propnum = 3000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 12,propname = "超级加倍",propnum = 3,propid = 33,imgpath = "img_double_ddzyh.png"},
    {day = 13,propname = "金豆",propnum = 3000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 14,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 15,propname = "黄宝石",propnum = 5,propid = 12,imgpath = "img_diamond4_forge_ddzyh.png"},
    {day = 16,propname = "金豆",propnum = 4000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 17,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 18,propname = "金豆",propnum = 4000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 19,propname = "钻石",propnum = 3,propid = 2,imgpath = "shop_diamond2_ddzyh.png"},
    {day = 19,propname = "金豆",propnum = 4000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 20,propname = "金豆",propnum = 5000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 22,propname = "记牌器",propnum = 3,propid = 32,imgpath = "icon_card_sign_ddzyh.png"},
    {day = 23,propname = "超级加倍",propnum = 3,propid = 33,imgpath = "img_double_ddzyh.png"},
    {day = 24,propname = "金豆",propnum = 5000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 25,propname = "金豆",propnum = 5000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 26,propname = "紫宝石",propnum = 5,propid = 13,imgpath = "img_diamond2_forge_ddzyh.png"},
    {day = 27,propname = "超级加倍",propnum = 3,propid = 33,imgpath = "img_double_ddzyh.png"},
    {day = 28,propname = "金豆",propnum = 5000,propid = 1,imgpath = "img_beans_ddzyh.png"},
    {day = 29,propname = "钻石",propnum = 3,propid = 2,imgpath = "shop_diamond2_ddzyh.png"},
    {day = 30,propname = "彩宝石",propnum = 5,propid = 14,imgpath = "icon_gem_sign_ddzyh.png"},
}
return SignInCfg