---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/28 15:57
---

-- 游戏消息命令码

local cmd_code = {
    MDM_GF_FRAME = 100,                     -- 框架消息
    SUB_GF_GAME_OPTION = 1,                 -- 场景消息
    SUB_GF_USER_READY = 2,                  -- 用户准备
    SUB_GF_GAME_SCENE = 101,                -- 场景消息

    MDM_CS_MAIN_LOGIC = 1000,               -- 主逻辑
    MDM_CS_GAME_LOGIC = 2000,               -- 游戏逻辑

    SUB_G_USER_LOGIN = 1001,                -- 用户登入
    SUB_G_USER_DISCONNECTED = 1002,         -- 用户断线
    SUB_G_USER_RECONNECT = 1003,            -- 用户重连

    MDM_GR_USER = 3,                        -- 用户消息
    SUB_CS_C_USER_ENTER = 1,                -- 用户进入
    SUB_CS_C_USER_LEAVE = 2,                -- 用户登出
    SUB_GR_USER_CHAIR_REQ = 10,             -- 用户请求一个位置(快速坐下)

    MDM_GF_GAME = 200,                      -- 游戏消息

    SUB_GAME_START = 100,                   -- 大厅业务消息
    SUB_CS_GAME_ENTER = 101,                -- 进入游戏(请求)
    SUB_SC_GAME_ENTER = 102,                -- 进入游戏(响应)

    SUB_CS_GAME_RECONNECT = 103,            -- 游戏重连(请求)
    SUB_SC_GAME_RECONNECT = 104,            -- 游戏重连(响应)

    SUB_CS_TREASURE_BOX = 105,              --用户宝箱列表消息（请求）
    SUB_SC_TREASURE_BOX = 106,              --用户宝箱列表消息(响应)

    SUB_CS_TREASURE_BOX_OPEN = 107,         --开宝箱消息（请求）
    SUB_SC_TREASURE_BOX_OPEN = 108,         --开宝箱消息（响应）

    SUB_CS_BOX_EXCHANGE = 109,              --宝箱兑换消息（请求）
    SUB_SC_BOX_EXCHANGE = 110,              --宝箱兑换消息（响应）

    SUB_CS_MONSTER_BOOKS = 111,             --图鉴列表(请求)
    SUB_SC_MONSTER_BOOKS = 112,             --图鉴列表(响应)

    SUB_CS_MONSTER_BOOKS_REWARD = 113,      --图鉴奖励(请求)
    SUB_SC_MONSTER_BOOKS_REWARD = 114,      --图鉴奖励(响应)

    SUB_CS_MILESTONE = 115,                 --里程碑(请求)
    SUB_SC_MILESTONE = 116,                 --里程碑(响应)

    SUB_CS_MILESTONE_REWARD = 117,          --里程碑奖励(请求)
    SUB_SC_MILESTONE_REWARD = 118,          --里程碑奖励(响应)

    SUB_CS_ENERGY_RECOVERY = 119,           --体力恢复(请求)
    SUB_SC_ENERGY_RECOVERY = 120,           --体力恢复(响应)

    SUB_CS_SIGN_LIST = 121,                 --签到列表(请求)
    SUB_SC_SIGN_LIST = 122,                 --签到列表(响应)

    SUB_CS_USER_SIGN = 123,                 --用户签到(请求)
    SUB_SC_USER_SIGN = 124,                 --用户签到(响应)

    SUB_CS_DAILY_TASK_LIST = 125,           --每日任务列表(请求)
    SUB_SC_DAILY_TASK_LIST = 126,           --每日任务列表(响应)

    SUB_CS_DAILY_TASK_REWARD = 127,         --每日任务领取奖励(请求)
    SUB_SC_DAILY_TASK_REWARD = 128,         --每日任务领取奖励(响应)

    SUB_CS_USER_SCENE = 129,                -- 最新通关数据（请求）
    SUB_SC_USER_SCENE = 130,                -- 最新通关数据（响应）

    SUB_SC_USER_SCENE = 130,                -- 最新通关数据（响应）

    SUB_CS_HANGUP_REWARD = 131,             -- 离线收益（请求）
    SUB_SC_HANGUP_REWARD = 132,             -- 离线收益（响应）
    SUB_CS_HANGUP_INFO = 133,               -- 离线收益信息（响应）
    SUB_SC_HANGUP_INFO = 134,               -- 离线收益信息（响应）

    SUB_CS_USER_VIEW = 135,                 -- 请求用户个人信息（请求）
    SUB_SC_USER_VIEW = 136,                 -- 请求用户个人信息（响应）

    SUB_CS_USER_VIEW_MODIFY = 137,          -- 修改昵称头像（请求）
    SUB_SC_USER_VIEW_MODIFY = 138,          -- 修改昵称头像（响应）

    SUB_ROLE_START = 150,                   -- 角色消息

    SUB_CS_ROLE_LINEUP_SWITCH = 151,        -- 阵容切换(请求)
    SUB_SC_ROLE_LINEUP_SWITCH = 152,        -- 阵容切换(响应)

    SUB_CS_ROLE_LEVELUP = 153,              -- 角色升级(请求)
    SUB_SC_ROLE_LEVELUP = 154,              -- 角色升级(响应)

    SUB_CS_ROLE_RANKUP = 155,               -- 角色升阶(请求)
    SUB_SC_ROLE_RANKUP = 156,               -- 角色升阶(响应)

    SUB_CS_ROLE_CHIP_CONVERT = 157,         -- 角色碎片转换(请求)
    SUB_SC_ROLE_CHIP_CONVERT = 158,         -- 角色碎片转换(响应)

    SUB_CS_ROLE_LINEUP_DISPATCH = 159,      -- 角色出战(请求)
    SUB_SC_ROLE_LINEUP_DISPATCH = 160,      -- 角色出战(响应)

    SUB_CS_ROLE_ATTR_INFO = 161,                 -- 角色属性信息(请求)
    SUB_SC_ROLE_ATTR_INFO = 162,                 -- 角色属性信息(响应

    SUB_CS_ROLE_INFO = 163,                 -- 角色信息(请求)
    SUB_SC_ROLE_INFO = 164,                 -- 角色信息(响应)

    SUB_CS_ROLE_LIST = 165,                 -- 角色列表(请求)
    SUB_SC_ROLE_LIST = 166,                 -- 角色列表(响应)

    SUB_EQUIP_START = 200,                  -- 装备消息
    SUB_CS_EQUIP_MERGE = 201,               -- 装备合成（请求）
    SUB_SC_EQUIP_MERGE = 202,               -- 装备合成（响应）
    SUB_CS_EQUIP_RESET = 203,               -- 装备属性重置（请求）
    SUB_SC_EQUIP_RESET = 204,               -- 装备属性重置（响应）
    SUB_CS_EQUIP_CONVERT = 205,             -- 装备转换（请求）
    SUB_SC_EQUIP_CONVERT = 206,             -- 装备转换（响应）
    SUB_CS_EQUIP_LIST = 207,                -- 装备列表(请求)
    SUB_SC_EQUIP_LIST = 208,                -- 装备列表(响应)
    SUB_CS_EQUIP_WEAR = 209,                -- 装备替换(请求)
    SUB_SC_EQUIP_WEAR = 210,                -- 装备替换(响应)

    SUB_BATTLE_START = 300,                 -- 游戏战斗消息
    SUB_CS_BATTLE_START = 301,              -- 游戏开始(请求)
    SUB_SC_BATTLE_START = 302,              -- 游戏开始(响应)
    SUB_CS_BATTLE_NEXT = 303,               -- 下一关(请求)
    SUB_SC_BATTLE_NEXT = 304,               -- 下一关(响应)
    SUB_CS_ROLE_ABILITY_CHOICE = 305,       -- 3选2选择技能(请求)
    SUB_SC_ROLE_ABILITY_CHOICE = 306,       -- 3选2选择技能(响应)
    SUB_CS_BATTLE_EXIT = 307,               -- 退出战斗(请求)
    SUB_SC_BATTLE_EXIT = 308,               -- 退出战斗(响应)
    SUB_CS_BATTLE_OVER = 309,               -- 战斗结束(请求)
    SUB_SC_BATTLE_OVER = 310,               -- 战斗结束(响应)
    SUB_CS_BATTLE_BLOOD_DEDUCE = 311,       -- 城墙血量扣除(请求)
    SUB_SC_BATTLE_BLOOD_DEDUCE = 312,       -- 城墙血量扣除(响应)


    SUB_CS_ABILITY_LIST = 313,              -- 3选2技能列表(请求)
    SUB_SC_ABILITY_LIST = 314,              -- 3选2技能列表(响应)

    SUB_CS_ABILITY_CELL_UNLOCK = 315,              -- 3选2技能槽解锁(请求)
    SUB_SC_ABILITY_CELL_UNLOCK = 316,              -- 3选2技能槽解锁(响应)

    SUB_CS_ROLE_ABILITY_LIST = 317,         -- 角色技能列表(请求)
    SUB_SC_ROLE_ABILITY_LIST = 318,         -- 角色技能列表(响应)

    SUB_CS_USER_SNAPSHOT = 319,             -- 处理快照信息(请求)
    SUB_SC_USER_SNAPSHOT = 320,             -- 处理快照信息(响应)

    SUB_CS_MOPPINGUP_SNAPSHOT = 321,        -- 扫荡(请求)
    SUB_SC_MOPPINGUP_SNAPSHOT = 322,        -- 扫荡(响应)

    SUB_CS_GAME_REVIVE = 323,             -- 游戏复活(请求)
    SUB_SC_GAME_REVIVE = 324,             -- 游戏复活(响应)

    SUB_CS_ABILITY_REFRESH = 325,             -- 3选2技能列表刷新(请求)
    SUB_SC_ABILITY_REFRESH = 326,             -- 3选2技能列表刷新(响应)

    SUB_CS_GAME_REVIVE_TIMES = 327,           -- 游戏复活次数(请求)
    SUB_SC_GAME_REVIVE_TIMES = 328,           -- 游戏复活次数(响应)

    SUB_CS_Use_User_Skill = 329,           -- 使用道具技能(请求)
    SUB_SC_Use_User_Skill = 330,           -- 使用道具技能(响应)

    SUB_CS_Rank_Activity = 450,             -- 排行榜活动(请求)
    SUB_SC_Rank_Activity = 451,             -- 排行榜活动(响应)
    SUB_CS_Rank_List = 452,                 -- 排行榜排名(请求)
    SUB_SC_Rank_List = 453,                 -- 排行榜排名(响应)
    SUB_CS_Rank_Award = 454,                -- 排行榜奖励(请求)
    SUB_SC_Rank_Award = 455,                -- 排行榜奖励(响应)

    PUSH_START = 800,                       -- 主动推送
    PUSH_USER_COIN = 801,                   -- 金币推送
    PUSH_USER_GEM = 802,                    -- 钻石推送
    PUSH_DAILY_TASK_CHANGE = 803,           -- 每日任务变化推送
    PUSH_PROPS_CHANGE = 804,                -- 道具变化推送
    PUSH_RECHARGE_SUCCESS = 807,            -- 充值成功
    PUSH_ROLE_COMBAT_CHANGE = 808,          -- 角色战力推送

    SUB_CS_GAME_END = 999,                  -- 游戏结束
}

return cmd_code