---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/6/1 15:20
---

local EquipGetView = class("EquipGetView", ViewBase)

function EquipGetView:ctor(para)
    self:enableNodeEvents()
    self:initData(para)
end

function EquipGetView:onEnter()
    self:initView()
    self:addNotify()
end

function EquipGetView:initData(para)
    self.roleId = para.roleId or 1
    self.equipId = para.equipId or 1102
    self.equipType = para.equipType or 2
end

function EquipGetView:initView()
    local para = {
        csb = JunTuanCfg.csbCfg.common.getEquipView,
        setSize = true
    }
    local ui = ViewBase:createCSB(para)
    self:addChild(ui)

    local panel_blue = ui:getChildByName("Panel_blue")
    local img_bg = panel_blue:getChildByName("img_bg"):show()
    img_bg:loadTexture("res/JunTuan/img/bg_pop_set_jtdzz.png", 0)
    img_bg:setScale9Enabled(true)
    img_bg:setCapInsets(cc.rect(10, 10, 553, 562))

    local img_light = panel_blue:getChildByName("img_light")
    img_light:runAction(cc.RepeatForever:create(cc.RotateBy:create(0.1, 20)))

    local panel_equip = panel_blue:getChildByName("Panel_equip")
    GameTool:setEquipImgById(self.equipId, panel_equip)
    local panel_detail = panel_blue:getChildByName("Panel_detail")
    local txt_tip = panel_blue:getChildByName("Text_tip")
    local txt_equip = panel_equip:getChildByName("Text_equip")
    self.txt_tip = txt_tip
    self.txt_equip = txt_equip
    self:initPanelDetail(panel_detail)

    local btn_share = panel_blue:getChildByName("btn_share")
    local btn_close = panel_blue:getChildByName("Panel_close")
    local function btnCall()
        self:destroyAni(panel_blue, function ()
            self:removeFromParent()
        end)
    end
    ExternalTools:addBtnTouchEventListener(btn_share, btnCall)
    ExternalTools:addBtnTouchEventListener(btn_close, btnCall)
end

function EquipGetView:initPanelDetail(panel)
    local data = GameTool:getEquipTxtInfo(self.roleId, self.equipType)
    local txt_type = panel:getChildByName("Text_detail_1")
    local txt_job = panel:getChildByName("Text_detail_2")
    local txt_atk = panel:getChildByName("Text_detail_3")
    local txt_value = panel:getChildByName("Text_detail_4")
    txt_type:setString(data.typeStr)
    txt_job:setString(data.roleStr)

    local equipCfg = data[self.roleId]
    local des = equipCfg[self.equipType + 3]
    self.txt_tip:setString(des)
    self.txt_equip:setString(equipCfg[self.equipType])
end

function EquipGetView:addNotify()

end

function EquipGetView:removeNotify()

end

function EquipGetView:onExit()
    self:removeNotify()
end

return EquipGetView