---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/6/24 11:27
---

-- 提示界面
local GameTipView = class("GameTipView", ViewBase)

function GameTipView:ctor(para)
    self:enableNodeEvents()
    self:initData(para)
end

function GameTipView:onEnter()
    self:initView()
    self:addNotify()
end

function GameTipView:initData(para)
    if para then
        self.call = para.call
    end
end

function GameTipView:initView()
    local para = {
        csb = JunTuanCfg.csbCfg.GameView.game_tip,
        setSize = true
    }
    local ui = ViewBase:createCSB(para)
    self:addChild(ui)

    local panel_black = ui:getChildByName("Panel_black")
    local panel_main = panel_black:getChildByName("Panel_main")
    self:createAni(panel_main)

    local panel_tittle = panel_main:getChildByName("Panel_tittle")
    local panel_diamond = panel_main:getChildByName("Panel_diamond")
    local panel_tip = panel_main:getChildByName("Panel_tip")
    self.img_prop = panel_diamond:getChildByName("img_diamond"):hide()
    self.txt_prop = panel_diamond:getChildByName("Text_num"):hide()
    self.txt_title = panel_tittle:getChildByName("Text_tittle")
    self.txt_tip = panel_main:getChildByName("Text_tip")
    self.txt_title_tip = panel_tip:getChildByName("Text_tip_1")
    self.txt_tip_content = panel_tip:getChildByName("Text_tip_2")
    self:initPanelContent(panel_diamond)

    local btn_close = panel_main:getChildByName("btn_close")
    local btn_ok = panel_main:getChildByName("btn_buy")
    local function btnCall()
        self:destroyAni(panel_main, function()
            if self.call then
                self.call()
            end
            self:removeFromParent(true)
        end)
    end
    ExternalTools:addBtnTouchEventListener(btn_ok, btnCall)
    ExternalTools:addBtnTouchEventListener(btn_close, btnCall)
end

function GameTipView:initPanelContent(panel)
    local s = panel:getContentSize()
    --local info = JunTuanCfg.spineAni.EffectAni.cardBtn
    --local ani_week = AnimationMgr:createSpine(info.file)
    --ani_week:setAnimation(0, info.names[1], true)
    --ani_week:setPosition(cc.p(s.width / 2, s.height / 2))
    local ani_week = cc.Sprite:createWithSpriteFrameName("newUserCard.png")
    ani_week:setPosition(cc.p(s.width / 2, s.height / 2))
    panel:addChild(ani_week)
end

function GameTipView:addNotify()

end

function GameTipView:removeNotify()

end

function GameTipView:onExit()
    self:removeNotify()
end

return GameTipView