---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/9 10:19
---

local Cfg = {
    plist = {
        "res/JunTuan/plist/1a10ebc6c",
        "res/JunTuan/plist/1a3261a6c",
        "res/JunTuan/plist/1abd60d94",
        "res/JunTuan/plist/1d5d89baf",
        "res/JunTuan/plist/1d556bb12",
        "res/JunTuan/plist/1e67c1036",
        "res/JunTuan/plist/18b323ccc",
        "res/JunTuan/plist/19fc2eb50",
        "res/JunTuan/plist/134b179c8",
        "res/JunTuan/plist/161a90d94",
        "res/JunTuan/plist/1761a4d8a",
        "res/JunTuan/plist/1774e1ffe",
        "res/JunTuan/plist/14063ce2e",
        "res/JunTuan/plist/16744fe05",
        "res/JunTuan/plist/18783edf3",

        "res/JunTuan/plist/field_jtdzz",
        "res/JunTuan/plist/hero_jtdzz",
        "res/JunTuan/plist/home_jtdzz",
        "res/JunTuan/plist/reward_jtdzz",
        "res/JunTuan/plist/pop_jtdzz",
        "res/JunTuan/plist/game_jtdzz",
        "res/JunTuan/plist/public_jtdzz",
        "res/JunTuan/plist/gift_jtdzz",
        "res/JunTuan/plist/guide",
        "res/JunTuan/plist/money",
    },

    spineAniCache = {
        "res/JunTuan/spine/dici",
        "res/JunTuan/spine/kaishianniu",
        "res/JunTuan/spine/los",
        "res/JunTuan/spine/win",
        "res/JunTuan/spine/shangdian_kaibaoxiang",


        "res/JunTuan/spine/enemy/baoxiangguai",
        "res/JunTuan/spine/enemy/chuguai",
    },

    bulletCfg = {
        [Define.bulletType.ult_1] = "ult1.png",
        [Define.bulletType.atk_1] = "jian.png",
        [Define.bulletType.ult_2] = "ult2.png",
        [Define.bulletType.atk_2] = "shellBullet.png",
        [Define.bulletType.ult_3] = "exp1.png",
        [Define.bulletType.atk_3] = "exp1.png",
        [Define.bulletType.ult_4] = "1.png",
        [Define.bulletType.atk_4] = "bullet_fire0.png",
        [Define.bulletType.ult_5] = "ult5.png",
        [Define.bulletType.atk_5] = "dartBullet.png",
        [Define.bulletType.ult_6] = "exp1.png",
        [Define.bulletType.atk_6] = "exp1.png",
    },

    csbCfg = {
        scene = {
            loadingScene = "res/JunTuan/LoadingScene.csb",
        },
        loadingView = {
            phoneView = "res/JunTuan/login_phone.csb",
        },
        common = {
            getRewardView = "res/JunTuan/happy_get.csb",            -- 通用奖励弹窗
            getEquipView = "res/JunTuan/unlock_equip.csb",          -- 获得装备弹窗
        },
        mainView = {
            main = "res/JunTuan/MainScene.csb",
            modify_head = "res/JunTuan/change_head.csb",              -- 修改头像
            modify_nick = "res/JunTuan/nickname_revise.csb",          -- 修改昵称
        },
        shopView = {
            shop_main = "res/JunTuan/shopLayer.csb",
            shop_buy = "res/JunTuan/buy_gem.csb",                   -- 购买钻石界面
            shop_pay = "res/JunTuan/buy_pay.csb",                   -- 支付界面
            shop_buy_gold = "res/JunTuan/buy_gold.csb",             -- 购买金币界面
            shop_buy_energy = "res/JunTuan/buy_energy.csb",         -- 购买体力界面
            shop_week_card = "res/JunTuan/card_week.csb",           -- 购买周卡界面
            shop_month_card = "res/JunTuan/card_month.csb",         -- 购买月卡界面
        },
        heroView = {
            hero_main = "res/JunTuan/heroLayer.csb",
            hero_rank_detail = "res/JunTuan/hero_promotion_detail.csb",
            hero_rank_up = "res/JunTuan/hero_promotion.csb",
            hero_combat = "res/JunTuan/hero_combat.csb",
            hero_pieces = "res/JunTuan/hero_pieces.csb",
            hero_equip = "res/JunTuan/hero_equip.csb",
            hero_merge = "res/JunTuan/hero_new_equip.csb",          -- 装备合成
            hero_rank_show = "res/JunTuan/unlock_rank.csb",         -- 军衔进阶展示
        },
        homeView = {
            home_main = "res/JunTuan/homeLayer.csb",
            hand_book = "res/JunTuan/handbookScene.csb",        -- 怪物图鉴
            hand_detail = "res/JunTuan/handbook_detail.csb",    -- 图鉴详情
            milepost = "res/JunTuan/milepost.csb",              -- 里程碑
            offline = "res/JunTuan/offline_revenue.csb",        -- 离线收益
            set_scene = "res/JunTuan/setScene.csb",             -- 设置界面
            sign_week = "res/JunTuan/sign_week.csb",            -- 签到
            task_daily = "res/JunTuan/task_daily.csb",          -- 每日任务
            rank_list = "res/JunTuan/ranking_list.csb"         -- 排行榜界面
        },
        GameView = {
            loading = "res/JunTuan/GameLoading.csb",            -- loadingView
            game_view = "res/JunTuan/GameScene.csb",            -- 游戏主界面
            three_two = "res/JunTuan/Skill_Three_Tow.csb",      -- 三选二技能
            game_fail = "res/JunTuan/Game_fail.csb",            -- 询问复活界面
            game_guide = "res/JunTuan/GuideLayer.csb",          -- 新手指引界面
            game_tip = "res/JunTuan/Game_tip2.csb",             -- 提示界面
            prop_sm = "res/JunTuan/prop_explain.csb",           -- 道具说明
        },
        GiftBag = {
            newUser = "res/JunTuan/gift_novice.csb",            -- 新手礼包
        }
    },

    spineAni = {
        openBoxAni = {
            file = "res/JunTuan/spine/shangdian_kaibaoxiang",
            names = { "1", "2", "3", "4" },
        },
        btnStartAni = {
            file = "res/JunTuan/spine/kaishianniu",
            names = { "animation" },
        },
        roleSpAni = {
            names = {
                zmdj = "zhengmian_daiji",       -- 正面待机
                cmdj = "cemian_daiji",          -- 侧面待机
                zmgj = "zhengmian",             -- 正面攻击
                cmgj = "cemian",                -- 侧面攻击
            }
        },
        gameOverAni = {
            win = {
                file = "res/JunTuan/spine/win",
                names = { "animation", "huangyeqiusheng", "juejingshuchu" },
            },
            lose = {
                file = "res/JunTuan/spine/los",
                names = { "animation" },
            },
        },
        EffectAni = {
            crazy = {
                file = "res/JunTuan/spine/effect/kuangbao",
                names = { "kuangbao", "tishi" },
            },
            frozen = {
                file = "res/JunTuan/spine/effect/bingdong",
                names = { "tangchu", "bingdong" },
            },
            missile = {
                file = "res/JunTuan/spine/effect/daodanbaozha",
                names = { "baozha", "tishi", "weiyan" },
            },
            cardBtn = {
                file = "res/JunTuan/spine/effect/yuekai-tx",
                names = { "zhouka", "yueka" },
            },
        }
    }
}

return Cfg