---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/15 18:05
---

local Define = {}

Define.dartCombat = {
    0,
    1350,
    2200,
    3500,
    4400,
    5250,
    6400,
    7400,
    8400,
    1e4
}

Define.state = {
    -- 怪物状态
    born = "born",
    move = "move",
    repel = "repel",
    die = "die",
    frozen = "frozen",
    stop = "stop",

    -- 英雄状态
    ult = "ult",
    attack = "attack",

    -- 游戏状态
    running = "running",
    pause = "pause",
}

Define.bulletType = {
    atk_1 = 1,
    atk_2 = 2,
    atk_3 = 3,
    atk_4 = 4,
    atk_5 = 5,
    atk_6 = 6,
    ult_1 = 7,
    ult_2 = 8,
    ult_3 = 9,
    ult_4 = 10,
    ult_5 = 11,
    ult_6 = 12,
}

Define.recoveryKill = 5     -- 技能自然恢复量
Define.skillBallGet = 0.3   -- 技能球掉落概率

Define.SKILL_TYPE_AREA = 0  -- 范围技能
Define.SKILL_TYPE_LINE = 1  -- 指向技能

Define.ENUM_REWARD_TYPE = {
    CHIPS = 1,
    EQUIPS = 2,
    PET_EGG = 3,
    PET = 4,
    COINS = 5,
    GEM = 6,
    ENERGY = 7,
    BOX = 8,
};

Define.ENUM_REDTIS_TYPE = {
    MONSTERBOOK = 1,
    MILESTONE = 2,
    SIGN = 3
};

Define.ENUM_GEM_COST = {
    CHIP_CHANGE = 1,        -- 碎片转换
    EQUIP_CHANGE = 2,       -- 装备转换
    EQUIP_RESET = 3,        -- 重置装备
    SKILL_RESET = 4,        -- 刷新技能
    SKILL_UNLOCK = 5,       -- 解锁技能槽
    GAME_REVIVE = 6,       -- 闯关复活
}

-- 配置表枚举
Define.ENUM_CFG_KEY = {
    --MILEPOST_CFG = "MilestoneTaskInfo",     -- 里程碑配置
    SHOP_CFG = "RechargeProductInfo",       -- 商城配置
    GEM_COST = "CostInfo",                  -- 消耗钻石配置表
    EXCHANGE_BOX = "ExchangeBoxInfo",       -- 宝箱兑换配置表
    RECHARGE_INFO = "RechargeRewardInfo",   -- 月卡、周卡配置表
    MONSTER_INFO = "MonsterTypeBuffInfo",   -- 怪物附加buff配置表
    RANK_REWARD_INFO = "RankActivityRewardConfig",   -- 排行榜奖励配置表
}

-- 礼包ptype配置
Define.ENUM_GIFT_BAG_TYPE = {
    WEEK_CARD = 1,
    MONTH_CARD = 2,
    NEW_USER = 3,
}

Define.ShopUnlock = 3       -- 开宝箱限制
Define.TaskUnlock = 5       -- 每日任务限制

-- 开宝箱限制
Define.BoxUnlock = {
    [1] = 0, [2] = 3, [3] = 3, [4] = 5
}

Define.CardPrivilegeWeek = { 1, 2, 3, 5 }       -- 周卡的特权
Define.CardPrivilegeMonth = { 1, 2, 3, 4, 6, 7 }   -- 月卡的特权
-- 游戏特权
Define.CardTxtCfg = {
    "离线收益金币翻倍",
    "免费解锁所有技能槽",
    "每次三选二免费刷新技能1次",
    "免费复活",
    "游戏两倍加速",
    "游戏三倍加速",
    "免费领取里程碑左侧奖励"
}

Define.EnergyCost = 5

Define.CARDS_CFG = {
    WEEK_ID = 7,
    MONTH_ID = 8,
}

-- 用户行为
Define.USER_ACTION = {
    recharge_view = {
        eventID = 1,
        eventName = "浏览充值界面"
    },
    energy_view = {
        eventID = 2,
        eventName = "浏览体力兑换界面"
    },
    money_view = {
        eventID = 3,
        eventName = "浏览金币兑换界面"
    },
    weedCard_view = {
        eventID = 4,
        eventName = "浏览周卡界面"
    },
    monthCard_view = {
        eventID = 5,
        eventName = "浏览月卡界面"
    },
    newUser_view ={
        eventID = 6,
        eventName = "浏览新手礼包界面"
    },
    openPay_view ={
        eventID = 7,
        eventName = "打开支付界面"
    },
    aliPay_view ={
        eventID = 8,
        eventName = "点击支付宝支付"
    },
    wechatPay_view ={
        eventID = 9,
        eventName = "点击微信支付"
    },
}

Define.CRAZY_UP = 2

-- 道具id配置
Define.PropSkillIdx = {
    crazy = 1,
    frozen = 2,
    missile = 3,
}
-- 道具说明配置
Define.PropSkillDes = {
    [Define.PropSkillIdx.crazy] = "狂暴：所有角色攻速翻倍，技能恢复翻倍，持续5秒，冷却60秒。",
    [Define.PropSkillIdx.frozen] = "冰封：冰封所有怪物，持续时间3秒，冷却时间60秒。",
    [Define.PropSkillIdx.missile] = "导弹：战术轰炸，对所有怪物造成血量上限50%的伤害！！！冷却时间300秒。",
}
-- 导弹伤害百分比
Define.MISSILE_DAMAGE = 0.5

return Define