---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/27 10:16
---

local GameDataCfg = {}

-- 怪物碰撞圆配置
GameDataCfg.enemyRadiusInfo = {
    45, 45, 45, 45, 45, 45, 45, 35, 45, 45, 45,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
}

-- 子弹碰撞半径
GameDataCfg.bulletRadiusInfo = {
    [Define.bulletType.atk_1] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.ult_1] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.atk_2] = { bounding_radius = 40, bounding_count = 1 },
    [Define.bulletType.ult_2] = { bounding_radius = 40, bounding_count = 1 },
    [Define.bulletType.atk_3] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.ult_3] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.atk_4] = { bounding_radius = 48, bounding_count = 4 },
    [Define.bulletType.ult_4] = { bounding_radius = 20, bounding_count = 19 },
    [Define.bulletType.atk_5] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.ult_5] = { bounding_radius = 30, bounding_count = 1 },
    [Define.bulletType.atk_6] = { bounding_radius = 40, bounding_count = 1 },
    [Define.bulletType.ult_6] = { bounding_radius = 45, bounding_count = 1 },
}

-- 能对区域内多少个敌人造成伤害
GameDataCfg.canHitNum = { 1, 5, 1, 1, 1, 3 }

-- 子弹移动速度
GameDataCfg.bulletSpeed = { 600, 500, 1000, 600, 700, 600 }

-- 怪物血条Y坐标配置
GameDataCfg.enemyHpY = {
    70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
}

return GameDataCfg