---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/6/25 18:08
---

local GiftBagCfg = {}

-- 礼包productId配置
GiftBagCfg.productID_Cfg = {
    weekCard = 7,
    monthCard = 8,
    NewUserBag = 9,
}

return GiftBagCfg