---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/15 15:29
---

-- 图鉴配置
local IllustratedCfg = {}

-- 怪物图鉴配置
IllustratedCfg.MonsterCfg = {
    {
        MonsterID = 1,      -- 怪物id
        MonsterIcon = 8,    -- 怪物图标
        MonsterTypeID = { 1, 51 },  -- ？？
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },     -- 指定击杀数量
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }          -- 击杀到达指定数目后的奖励（钻石）
    },
    {
        MonsterID = 2,
        MonsterIcon = 5,
        MonsterTypeID = { 2, 52 },
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 3,
        MonsterIcon = 3,
        MonsterTypeID = { 4, 54 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 4,
        MonsterIcon = 4,
        MonsterTypeID = { 3, 53 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 5,
        MonsterIcon = 10,
        MonsterTypeID = { 5, 55 },
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 6,
        MonsterIcon = 6,
        MonsterTypeID = { 6, 56 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 7,
        MonsterIcon = 19,
        MonsterTypeID = { 17, 67 },
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 8,
        MonsterIcon = 15,
        MonsterTypeID = { 8, 58 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 9,
        MonsterIcon = 16,
        MonsterTypeID = { 7, 57 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 10,
        MonsterIcon = 21,
        MonsterTypeID = { 15, 65 },
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 11,
        MonsterIcon = 1,
        MonsterTypeID = { 9, 59 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 12,
        MonsterIcon = 2,
        MonsterTypeID = { 10, 60 },
        MonsterSkillNub = { 12, 600, 1500, 4800, 14400, 36e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 13,
        MonsterIcon = 17,
        MonsterTypeID = { 11, 61 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 14,
        MonsterIcon = 7,
        MonsterTypeID = { 12, 62 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 15,
        MonsterIcon = 20,
        MonsterTypeID = { 16, 66 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 16,
        MonsterIcon = 18,
        MonsterTypeID = { 13, 63 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    },
    {
        MonsterID = 17,
        MonsterIcon = 22,
        MonsterTypeID = { 14, 64 },
        MonsterSkillNub = { 9, 450, 1125, 3600, 10800, 27e3 },
        MonsterSkillReward = { 30, 50, 70, 100, 150, 200 }
    }
}

return IllustratedCfg