---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/15 15:16
---

local PetConfig = {}

-- 1类型宠物通过每日任务获得
-- 7类型宠物通过里程碑获得
-- 能够捕获的宠物类型
PetConfig.PetCatchModel = { 2, 8, 9, 10 }

-- 能够孵化的宠物类型
PetConfig.PetHatchModel = { 3, 4, 5, 6 }


return PetConfig