---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/5/8 16:48
---

-- 奖励id说明
--(1-6:对应类型的英雄碎片，501:金币，502:钻石，601-604:对应宝箱，1100 - 6310:对应装备，100101-101010:对应宠物)
PropID = {
    chip_1 = 1,         -- 英雄1碎片
    chip_2 = 2,         -- 英雄2碎片
    chip_3 = 3,         -- 英雄3碎片
    chip_4 = 4,         -- 英雄4碎片
    chip_5 = 5,         -- 英雄5碎片
    chip_6 = 6,         -- 英雄6碎片
    gold = 501,         -- 金币
    soul = 502,         -- 钻石
    egg = 503,          -- 宠物蛋
    box_1 = 601,        -- 白色宝箱
    box_2 = 602,        -- 绿色宝箱
    box_3 = 603,        -- 蓝色宝箱
    box_4 = 604,        -- 紫色宝箱

    week_card = 7,      -- 周卡
    month_card = 8,     -- 月卡
}

PropImg = {
    [PropID.box_1] = "img_reward_box1_shop_jtdzz.png",
    [PropID.box_2] = "img_reward_box2_shop_jtdzz.png",
    [PropID.box_3] = "img_reward_box3_shop_jtdzz.png",
    [PropID.box_4] = "img_reward_box4_shop_jtdzz.png",
    [PropID.gold] = "img_money_milepost_jtdzz.png",
    [PropID.soul] = "img_supply_soul_shop_jtdzz.png",
    [PropID.chip_1] = "img_gunner2_hero_jtdzz.png",
    [PropID.chip_2] = "img_gunner_hero_jtdzz.png",
    [PropID.chip_3] = "img_gunner5_hero_jtdzz.png",
    [PropID.chip_4] = "img_gunner6_hero_jtdzz.png",
    [PropID.chip_5] = "img_gunner3_hero_jtdzz.png",
    [PropID.chip_6] = "img_gunner4_hero_jtdzz.png",
}