---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/15 10:07
---

local SceneLevelCfg = {}

-- 场景配置
SceneLevelCfg.SceneCfg = {
    {
        SceneId = 1,
        Type = 1,
        Param = { 4e3 }
    },
    {
        SceneId = 2,
        Type = 2,
        Param = { 2e3, 3e3, 1e3, 0 }
    },
    {
        SceneId = 3,
        Type = 3,
        Param = {}
    },
    {
        SceneId = 4,
        Type = 4,
        Param = { 400 }
    },
    {
        SceneId = 6,
        Type = 1,
        Param = { 4e3 }
    },
    {
        SceneId = 7,
        Type = 2,
        Param = { 2e3, 3e3, 1e3, 0 }
    },
    {
        SceneId = 8,
        Type = 3,
        Param = {}
    },
    {
        SceneId = 9,
        Type = 4,
        Param = { 400 }
    },
    {
        SceneId = 11,
        Type = 1,
        Param = { 4e3 }
    },
    {
        SceneId = 12,
        Type = 2,
        Param = { 2e3, 3e3, 1e3, 0 }
    },
    {
        SceneId = 13,
        Type = 3,
        Param = {}
    },
    {
        SceneId = 14,
        Type = 4,
        Param = { 400 }
    },
    {
        SceneId = 15,
        Type = 5,
        Param = { 124 }
    },
    {
        SceneId = 16,
        Type = 6,
        Param = { 1e4 }
    },
    {
        SceneId = 17,
        Type = 7,
        Param = { 5e3 }
    },
    {
        SceneId = 18,
        Type = 8,
        Param = { 150 }
    },

}

return SceneLevelCfg