---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/5/7 17:01
---

local SceneNameCfg = {
    [1] = {
        Name = "暗夜之地",
        LevelNum = 5,
    },
    [2] = {
        Name = "背水一战",
        LevelNum = 8,
    },
    [3] = {
        Name = "巫师狂猎",
        LevelNum = 5,
    },
    [4] = {
        Name = "灰烬城堡",
        LevelNum = 20,
    },
    [5] = {
        Name = "星辰大海",
        LevelNum = 20,
    },
    [6] = {
        Name = "进击序章",
        LevelNum = 13,
    },
    [7] = {
        Name = "沧桑浩劫",
        LevelNum = 30,
    },
    [8] = {
        Name = "红月星耀",
        LevelNum = 30,
    },
    [9] = {
        Name = "冻土大陆",
        LevelNum = 13,
    },
    [10] = {
        Name = "黎明曙光",
        LevelNum = 30,
    },
    [11] = {
        Name = "创造毁灭",
        LevelNum = 30,
    },
    [12] = {
        Name = "狂热仪式",
        LevelNum = 13,
    },
    [13] = {
        Name = "混乱秩序",
        LevelNum = 30,
    },
    [14] = {
        Name = "落日余晖",
        LevelNum = 30,
    },
    [15] = {
        Name = "逆转乾坤",
        LevelNum = 13,
    },
    [16] = {
        Name = "审判降临",
        LevelNum = 30,
    },
    [17] = {
        Name = "圣光制裁",
        LevelNum = 30,
    },
    [18] = {
        Name = "嗜血狂暴",
        LevelNum = 13,
    },
    [19] = {
        Name = "守卫荣耀",
        LevelNum = 30,
    },
    [20] = {
        Name = "贪狼之力",
        LevelNum = 30,
    },
    [21] = {
        Name = "万物有灵",
        LevelNum = 13,
    },
    [22] = {
        Name = "为了正义",
        LevelNum = 30,
    },
    [23] = {
        Name = "暗影之月",
        LevelNum = 30,
    },
    [24] = {
        Name = "惩奸除恶",
        LevelNum = 13,
    },
    [25] = {
        Name = "虚空梦魇",
        LevelNum = 30,
    },
    [26] = {
        Name = "遗忘传说",
        LevelNum = 30,
    },
    [27] = {
        Name = "勇者必胜",
        LevelNum = 13,
    },
    [28] = {
        Name = "灾厄漩涡",
        LevelNum = 30,
    },
    [29] = {
        Name = "炙热锋芒",
        LevelNum = 30,
    },
    [30] = {
        Name = "咒术封印",
        LevelNum = 13,
    },
    [31] = {
        Name = "暗夜之地",
        LevelNum = 30,
    },
    [32] = {
        Name = "背水一战",
        LevelNum = 30,
    },
    [33] = {
        Name = "巫师狂猎",
        LevelNum = 13,
    },
    [34] = {
        Name = "灰烬城堡",
        LevelNum = 30,
    },
    [35] = {
        Name = "星辰大海",
        LevelNum = 30,
    },
    [36] = {
        Name = "进击序章",
        LevelNum = 13,
    },
    [37] = {
        Name = "沧桑浩劫",
        LevelNum = 30,
    },
    [38] = {
        Name = "红月星耀",
        LevelNum = 30,
    },
    [39] = {
        Name = "冻土大陆",
        LevelNum = 13,
    },
    [40] = {
        Name = "黎明曙光",
        LevelNum = 30,
    },
    [41] = {
        Name = "创造毁灭",
        LevelNum = 30,
    },
    [42] = {
        Name = "狂热仪式",
        LevelNum = 13,
    },
    [43] = {
        Name = "混乱秩序",
        LevelNum = 30,
    },
    [44] = {
        Name = "落日余晖",
        LevelNum = 30,
    },
    [45] = {
        Name = "逆转乾坤",
        LevelNum = 13,
    },
    [46] = {
        Name = "审判降临",
        LevelNum = 30,
    },
    [47] = {
        Name = "圣光制裁",
        LevelNum = 30,
    },
    [48] = {
        Name = "嗜血狂暴",
        LevelNum = 13,
    },
    [49] = {
        Name = "守卫荣耀",
        LevelNum = 30,
    },
    [50] = {
        Name = "贪狼之力",
        LevelNum = 30,
    },
    [51] = {
        Name = "万物有灵",
        LevelNum = 13,
    },
    [52] = {
        Name = "为了正义",
        LevelNum = 30,
    },
    [53] = {
        Name = "暗影之月",
        LevelNum = 30,
    },
    [54] = {
        Name = "惩奸除恶",
        LevelNum = 13,
    },
    [55] = {
        Name = "虚空梦魇",
        LevelNum = 30,
    },
    [56] = {
        Name = "遗忘传说",
        LevelNum = 30,
    },
    [57] = {
        Name = "勇者必胜",
        LevelNum = 13,
    },
    [58] = {
        Name = "灾厄漩涡",
        LevelNum = 30,
    },
    [59] = {
        Name = "炙热锋芒",
        LevelNum = 30,
    },
    [60] = {
        Name = "咒术封印",
        LevelNum = 13,
    }
}

return SceneNameCfg