---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/15 17:02
---

local SkillCfg = {}

-- 三选二技能配置表
SkillCfg.Skill_Three_Two = {
    {
        Id = 1,
        Icon = 1,
        Parm = {},
        SpecialSkillType = 1,
        SpecialSkillValue = 8e3,
        Repeat = 1,
        Weight = 900,
        WeightReduce = 300,
        SceneLimit = 3
    },
    {
        Id = 2,
        Icon = 2,
        Parm = {},
        SpecialSkillType = 5,
        SpecialSkillValue = 8e3,
        Repeat = 1,
        Weight = 900,
        WeightReduce = 300,
        SceneLimit = 3
    },
    {
        Id = 3,
        Icon = 3,
        Parm = { 125 },
        SpecialSkillType = 2,
        SpecialSkillValue = 8e3,
        Repeat = 1,
        Weight = 900,
        WeightReduce = 300,
        SceneLimit = 3
    },
    {
        Id = 4,
        Icon = 4,
        Parm = { 5e3 },
        SpecialSkillType = 1,
        SpecialSkillValue = 4e3,
        Repeat = 99,
        Weight = 3e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 5,
        Icon = 5,
        Parm = { 3e3 },
        SpecialSkillType = 3,
        SpecialSkillValue = 2400,
        Repeat = 3,
        Weight = 3e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 6,
        Icon = 6,
        Parm = { 1e4 },
        SpecialSkillType = 4,
        SpecialSkillValue = 8e3,
        Repeat = 99,
        Weight = 3e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 7,
        Icon = 7,
        Parm = { 5e3 },
        SpecialSkillType = 2,
        SpecialSkillValue = 4e3,
        Repeat = 3,
        Weight = 3e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 8,
        Icon = 8,
        Parm = { 100, 100 },
        SpecialSkillType = 1,
        SpecialSkillValue = 4e3,
        Repeat = 1,
        Weight = 1500,
        WeightReduce = 300,
        SceneLimit = 3
    },
    {
        Id = 9,
        Icon = 14,
        Parm = { 2500 },
        SpecialSkillType = 1,
        SpecialSkillValue = 4e3,
        Repeat = 99,
        Weight = 5e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 10,
        Icon = 15,
        Parm = { 1500 },
        SpecialSkillType = 3,
        SpecialSkillValue = 2400,
        Repeat = 3,
        Weight = 5e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 11,
        Icon = 16,
        Parm = { 5e3 },
        SpecialSkillType = 4,
        SpecialSkillValue = 8e3,
        Repeat = 99,
        Weight = 5e3,
        WeightReduce = 0,
        SceneLimit = 3
    },
    {
        Id = 12,
        Icon = 17,
        Parm = { 2500 },
        SpecialSkillType = 2,
        SpecialSkillValue = 4e3,
        Repeat = 3,
        Weight = 5e3,
        WeightReduce = 0,
        SceneLimit = 3
    }
}

-- 军衔等级技能加成配置
SkillCfg.Skill_Special = {
    {
        Id = 1,
        Role = 1,
        Lv = 0,
        Param1 = 14286, -- 技能伤害比列
        Param2 = 30,
        PowerHumanNum = 1e4,
        PowerBulletNum = 30                -- 技能子弹数
    },
    {
        Id = 2,
        Role = 1,
        Lv = 1,
        Param1 = 15469,
        Param2 = 36,
        PowerHumanNum = 1e4,
        PowerBulletNum = 36
    },
    {
        Id = 3,
        Role = 1,
        Lv = 2,
        Param1 = 16560,
        Param2 = 42,
        PowerHumanNum = 1e4,
        PowerBulletNum = 42
    },
    {
        Id = 4,
        Role = 1,
        Lv = 3,
        Param1 = 18973,
        Param2 = 48,
        PowerHumanNum = 1e4,
        PowerBulletNum = 48
    },
    {
        Id = 5,
        Role = 1,
        Lv = 4,
        Param1 = 27900,
        Param2 = 54,
        PowerHumanNum = 1e4,
        PowerBulletNum = 54
    },
    {
        Id = 6,
        Role = 1,
        Lv = 5,
        Param1 = 32163,
        Param2 = 60,
        PowerHumanNum = 1e4,
        PowerBulletNum = 60
    },
    {
        Id = 7,
        Role = 1,
        Lv = 6,
        Param1 = 38418,
        Param2 = 66,
        PowerHumanNum = 1e4,
        PowerBulletNum = 66
    },
    {
        Id = 8,
        Role = 1,
        Lv = 7,
        Param1 = 44558,
        Param2 = 72,
        PowerHumanNum = 1e4,
        PowerBulletNum = 72
    },
    {
        Id = 9,
        Role = 1,
        Lv = 8,
        Param1 = 53430,
        Param2 = 78,
        PowerHumanNum = 1e4,
        PowerBulletNum = 78
    },
    {
        Id = 10,
        Role = 1,
        Lv = 9,
        Param1 = 66964,
        Param2 = 84,
        PowerHumanNum = 1e4,
        PowerBulletNum = 84
    },
    {
        Id = 11,
        Role = 1,
        Lv = 10,
        Param1 = 102800,
        Param2 = 90,
        PowerHumanNum = 1e4,
        PowerBulletNum = 90
    },
    {
        Id = 12,
        Role = 2,
        Lv = 0,
        Param1 = 4228,
        Param2 = 30,
        PowerHumanNum = 28160,
        PowerBulletNum = 18
    },
    {
        Id = 13,
        Role = 2,
        Lv = 1,
        Param1 = 4882,
        Param2 = 31,
        PowerHumanNum = 30480,
        PowerBulletNum = 18
    },
    {
        Id = 14,
        Role = 2,
        Lv = 2,
        Param1 = 5660,
        Param2 = 33,
        PowerHumanNum = 33760,
        PowerBulletNum = 18
    },
    {
        Id = 15,
        Role = 2,
        Lv = 3,
        Param1 = 6847,
        Param2 = 35,
        PowerHumanNum = 36080,
        PowerBulletNum = 18
    },
    {
        Id = 16,
        Role = 2,
        Lv = 4,
        Param1 = 10588,
        Param2 = 37,
        PowerHumanNum = 38e3,
        PowerBulletNum = 18
    },
    {
        Id = 17,
        Role = 2,
        Lv = 5,
        Param1 = 13253,
        Param2 = 39,
        PowerHumanNum = 38960,
        PowerBulletNum = 18
    },
    {
        Id = 18,
        Role = 2,
        Lv = 6,
        Param1 = 17078,
        Param2 = 42,
        PowerHumanNum = 40400,
        PowerBulletNum = 18
    },
    {
        Id = 19,
        Role = 2,
        Lv = 7,
        Param1 = 20016,
        Param2 = 44,
        PowerHumanNum = 43120,
        PowerBulletNum = 18
    },
    {
        Id = 20,
        Role = 2,
        Lv = 8,
        Param1 = 25097,
        Param2 = 47,
        PowerHumanNum = 44400,
        PowerBulletNum = 18
    },
    {
        Id = 21,
        Role = 2,
        Lv = 9,
        Param1 = 29528,
        Param2 = 49,
        PowerHumanNum = 51520,
        PowerBulletNum = 18
    },
    {
        Id = 22,
        Role = 2,
        Lv = 10,
        Param1 = 45616,
        Param2 = 52,
        PowerHumanNum = 54400,
        PowerBulletNum = 18
    },
    {
        Id = 23,
        Role = 3,
        Lv = 0,
        Param1 = 19048,
        Param2 = 5,
        PowerHumanNum = 15e3,
        PowerBulletNum = 5
    },
    {
        Id = 24,
        Role = 3,
        Lv = 1,
        Param1 = 20641,
        Param2 = 6,
        PowerHumanNum = 15e3,
        PowerBulletNum = 6
    },
    {
        Id = 25,
        Role = 3,
        Lv = 2,
        Param1 = 22365,
        Param2 = 7,
        PowerHumanNum = 15e3,
        PowerBulletNum = 7
    },
    {
        Id = 26,
        Role = 3,
        Lv = 3,
        Param1 = 25439,
        Param2 = 8,
        PowerHumanNum = 15e3,
        PowerBulletNum = 8
    },
    {
        Id = 27,
        Role = 3,
        Lv = 4,
        Param1 = 37332,
        Param2 = 9,
        PowerHumanNum = 15e3,
        PowerBulletNum = 9
    },
    {
        Id = 28,
        Role = 3,
        Lv = 5,
        Param1 = 43509,
        Param2 = 10,
        PowerHumanNum = 15e3,
        PowerBulletNum = 10
    },
    {
        Id = 29,
        Role = 3,
        Lv = 6,
        Param1 = 51553,
        Param2 = 11,
        PowerHumanNum = 15e3,
        PowerBulletNum = 11
    },
    {
        Id = 30,
        Role = 3,
        Lv = 7,
        Param1 = 60315,
        Param2 = 12,
        PowerHumanNum = 15e3,
        PowerBulletNum = 12
    },
    {
        Id = 31,
        Role = 3,
        Lv = 8,
        Param1 = 72494,
        Param2 = 13,
        PowerHumanNum = 15e3,
        PowerBulletNum = 13
    },
    {
        Id = 32,
        Role = 3,
        Lv = 9,
        Param1 = 90081,
        Param2 = 14,
        PowerHumanNum = 15e3,
        PowerBulletNum = 14
    },
    {
        Id = 33,
        Role = 3,
        Lv = 10,
        Param1 = 142548,
        Param2 = 15,
        PowerHumanNum = 15e3,
        PowerBulletNum = 15
    },
    {
        Id = 34,
        Role = 4,
        Lv = 0,
        Param1 = 3462,
        Param2 = 2e3,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 35,
        Role = 4,
        Lv = 1,
        Param1 = 4129,
        Param2 = 2200,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 36,
        Role = 4,
        Lv = 2,
        Param1 = 4761,
        Param2 = 2400,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 37,
        Role = 4,
        Lv = 3,
        Param1 = 5803,
        Param2 = 2600,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 38,
        Role = 4,
        Lv = 4,
        Param1 = 8590,
        Param2 = 2800,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 39,
        Role = 4,
        Lv = 5,
        Param1 = 10337,
        Param2 = 3e3,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 40,
        Role = 4,
        Lv = 6,
        Param1 = 12983,
        Param2 = 3200,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 41,
        Role = 4,
        Lv = 7,
        Param1 = 15629,
        Param2 = 3400,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 42,
        Role = 4,
        Lv = 8,
        Param1 = 19192,
        Param2 = 3600,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 43,
        Role = 4,
        Lv = 9,
        Param1 = 24848,
        Param2 = 3800,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 44,
        Role = 4,
        Lv = 10,
        Param1 = 39231,
        Param2 = 4e3,
        PowerHumanNum = 45e3,
        PowerBulletNum = 1
    },
    {
        Id = 45,
        Role = 5,
        Lv = 0,
        Param1 = 3429,
        Param2 = 5,
        PowerHumanNum = 1e4,
        PowerBulletNum = 5
    },
    {
        Id = 46,
        Role = 5,
        Lv = 1,
        Param1 = 3654,
        Param2 = 6,
        PowerHumanNum = 1e4,
        PowerBulletNum = 6
    },
    {
        Id = 47,
        Role = 5,
        Lv = 2,
        Param1 = 3969,
        Param2 = 7,
        PowerHumanNum = 1e4,
        PowerBulletNum = 7
    },
    {
        Id = 48,
        Role = 5,
        Lv = 3,
        Param1 = 4532,
        Param2 = 8,
        PowerHumanNum = 1e4,
        PowerBulletNum = 8
    },
    {
        Id = 49,
        Role = 5,
        Lv = 4,
        Param1 = 6666,
        Param2 = 9,
        PowerHumanNum = 1e4,
        PowerBulletNum = 9
    },
    {
        Id = 50,
        Role = 5,
        Lv = 5,
        Param1 = 7703,
        Param2 = 10,
        PowerHumanNum = 1e4,
        PowerBulletNum = 10
    },
    {
        Id = 51,
        Role = 5,
        Lv = 6,
        Param1 = 9137,
        Param2 = 11,
        PowerHumanNum = 1e4,
        PowerBulletNum = 11
    },
    {
        Id = 52,
        Role = 5,
        Lv = 7,
        Param1 = 10751,
        Param2 = 12,
        PowerHumanNum = 1e4,
        PowerBulletNum = 12
    },
    {
        Id = 53,
        Role = 5,
        Lv = 8,
        Param1 = 12751,
        Param2 = 13,
        PowerHumanNum = 1e4,
        PowerBulletNum = 13
    },
    {
        Id = 54,
        Role = 5,
        Lv = 9,
        Param1 = 16054,
        Param2 = 14,
        PowerHumanNum = 1e4,
        PowerBulletNum = 14
    },
    {
        Id = 55,
        Role = 5,
        Lv = 10,
        Param1 = 25064,
        Param2 = 15,
        PowerHumanNum = 1e4,
        PowerBulletNum = 15
    },
    {
        Id = 56,
        Role = 6,
        Lv = 0,
        Param1 = 11278,
        Param2 = 10,
        PowerHumanNum = 19e3,
        PowerBulletNum = 10
    },
    {
        Id = 57,
        Role = 6,
        Lv = 1,
        Param1 = 12661,
        Param2 = 11,
        PowerHumanNum = 2e4,
        PowerBulletNum = 11
    },
    {
        Id = 58,
        Role = 6,
        Lv = 2,
        Param1 = 12739,
        Param2 = 13,
        PowerHumanNum = 21e3,
        PowerBulletNum = 13
    },
    {
        Id = 59,
        Role = 6,
        Lv = 3,
        Param1 = 15485,
        Param2 = 14,
        PowerHumanNum = 21e3,
        PowerBulletNum = 14
    },
    {
        Id = 60,
        Role = 6,
        Lv = 4,
        Param1 = 21681,
        Param2 = 16,
        PowerHumanNum = 22e3,
        PowerBulletNum = 16
    },
    {
        Id = 61,
        Role = 6,
        Lv = 5,
        Param1 = 24680,
        Param2 = 17,
        PowerHumanNum = 23e3,
        PowerBulletNum = 17
    },
    {
        Id = 62,
        Role = 6,
        Lv = 6,
        Param1 = 27867,
        Param2 = 19,
        PowerHumanNum = 24e3,
        PowerBulletNum = 19
    },
    {
        Id = 63,
        Role = 6,
        Lv = 7,
        Param1 = 38273,
        Param2 = 20,
        PowerHumanNum = 21e3,
        PowerBulletNum = 20
    },
    {
        Id = 64,
        Role = 6,
        Lv = 8,
        Param1 = 47661,
        Param2 = 22,
        PowerHumanNum = 2e4,
        PowerBulletNum = 22
    },
    {
        Id = 65,
        Role = 6,
        Lv = 9,
        Param1 = 72809,
        Param2 = 23,
        PowerHumanNum = 17e3,
        PowerBulletNum = 23
    },
    {
        Id = 66,
        Role = 6,
        Lv = 10,
        Param1 = 105628,
        Param2 = 25,
        PowerHumanNum = 18e3,
        PowerBulletNum = 25
    }
}

SkillCfg.Skill_Three_Two_Des = {
    [1] = {
        Name = "正向+1",
        Des = "正前方增加一个弹道"
    },
    [2] = {
        Name = "斜向+1",
        Des = "两侧斜向角度各增加一个弹道"
    },
    [3] = {
        Name = "连续射击",
        Des = "额外进行一轮射击"
    },
    [4] = {
        Name = "攻击",
        Des = "提升攻击属性"
    },
    [5] = {
        Name = "暴击率",
        Des = "提升暴击率"
    },
    [6] = {
        Name = "暴击伤害",
        Des = "提升暴击伤害"
    },
    [7] = {
        Name = "攻速",
        Des = "提升攻击速度"
    },
    [8] = {
        Name = "近攻",
        Des = "怪物距离越近，对其伤害越高"
    },
    [14] = {
        Name = "攻击",
        Des = "提升攻击属性"
    },
    [15] = {
        Name = "暴击率",
        Des = "提升暴击率"
    },
    [16] = {
        Name = "暴击伤害",
        Des = "提升暴击伤害"
    },
    [17] = {
        Name = "攻速",
        Des = "提升攻击速度"
    }
}

return SkillCfg