require("src.protobuf.support.wire_format")
require("src.protobuf.support.type_checkers")
require("src.protobuf.support.encoder")
require("src.protobuf.support.decoder")
require("src.protobuf.support.listener")
require("src.protobuf.support.containers")
require("src.protobuf.support.descriptor")
require("src.protobuf.support.containers")
require("src.protobuf.support.text_format")
require("src.protobuf.support.protobuf")

require("src.protobuf.PBLandlord_pb")
require("src.protobuf.Game_LandLord_pb")
require("src.protobuf.ServerStruct_Logon_pb")
require("src.protobuf.ServerStruct_Game_pb")
require("src.protobuf.ServerStruct_Chat_pb")
require("src.protobuf.ServerStruct_Other_pb")
require("src.protobuf.HttpInterfacePB_pb")

require("src.protobuf.Game_Fish_pb")
require("src.protobuf.Game_CannonFish_pb")

require("src.protobuf.GamePB_pb")
require("src.protobuf.PBPayInterface_pb")