---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/9 10:22
---

local AudioManager = class("AudioManager")

function AudioManager:initAudioMgr()
    self.effect = {
        click = "res/JunTuan/sound/click.mp3",                  -- 通用按钮点击
        lvUp = "res/JunTuan/sound/lvUp.mp3",
        over = "res/JunTuan/sound/over.mp3",
        playerLvUp = "res/JunTuan/sound/playerLvUp.mp3",
        start = "res/JunTuan/sound/start.mp3",                  -- 开始挑战
        bgm1 = "res/JunTuan/sound/bgm1.mp3",
        bgm2 = "res/JunTuan/sound/bgm2.mp3",
        bgm3 = "res/JunTuan/sound/bgm3.mp3",
        bgm4 = "res/JunTuan/sound/bgm4.mp3",
        bgm5 = "res/JunTuan/sound/bgm5.mp3",
        boss = "res/JunTuan/sound/boss.mp3",
        cannon = "res/JunTuan/sound/cannon.mp3",                -- 炮兵攻击
        cannon1 = "res/JunTuan/sound/cannon1.mp3",              -- 炮兵溅射攻击
        cannon2 = "res/JunTuan/sound/cannon2.mp3",
        firegun = "res/JunTuan/sound/firegun.mp3",              -- 喷火兵攻击
        huadong = "res/JunTuan/sound/huadong.mp3",              -- 滑动关卡
        huishou = "res/JunTuan/sound/huishou.mp3",              -- 掉落装备回收
        main = "res/JunTuan/sound/main.mp3",                    -- 大厅背景音乐
        openskill = "res/JunTuan/sound/openskill.mp3",          -- 打开三选二界面
        putdown = "res/JunTuan/sound/putdown.mp3",              -- 三选二选择技能
        unAtt = "res/JunTuan/sound/unAtt.mp3",                  -- 狙击兵攻击
        startMp3 = "res/JunTuan/sound/startMp3.mp3",            -- 副本
        wheel = "res/JunTuan/sound/wheel.mp3",                  -- 忍者攻击
        hit_toumao = "res/JunTuan/sound/hit_toumao.mp3",        -- 忍者技能
        skillmst = "res/JunTuan/sound/skillmst.mp3",            -- 宝箱怪变形
        hit_shejian = "res/JunTuan/sound/hit_shejian.mp3",      -- 弓箭手攻击
        special_fire = "res/JunTuan/sound/special_fire.mp3",    -- 喷火兵技能
        special_arrow = "res/JunTuan/sound/special_arrow.mp3",  -- 弓箭手技能
        hit_dici = "res/JunTuan/sound/hit_dici.mp3",            -- 女巫技能
        hit_dici2 = "res/JunTuan/sound/dici2.mp3",              -- 女巫攻击
        hit_dici3 = "res/JunTuan/sound/dici3.mp3",              -- 女巫攻击
        hit_dici4 = "res/JunTuan/sound/dici4.mp3",              -- 女巫攻击
    }

    local m_v = ViewBase:getMusicVolume()
    local s_v = ViewBase:getSoundVolume()
    ViewBase:setMusicVolume(m_v)
    ViewBase:setSoundVolume(s_v)
end

----------------------- music -----------------------
-- 大厅背景音乐
function AudioManager:playHomeMusic()
    ViewBase:playMusic(self.effect["main"])
end

-- 场景背景音乐
function AudioManager:playSceneMusic(id)
    if id >= 1 and id <= 5 then
        local name = string.format("res/JunTuan/sound/bgm%d.mp3", id)
        ViewBase:playMusic(name)
    end
end

-- 设置背景音乐声音大小
function AudioManager:setMusicVolume(value)
    ViewBase:setMusicVolume(value)
end
-----------------------------------------------------

----------------------- effect ----------------------
-- 按钮点击音系
function AudioManager:playBtnEffect()
    self:playSoundEffect("click")
end

function AudioManager:playSoundEffect(id)
    ViewBase:playEffect(self.effect[id])
end

function AudioManager:playEnemyDieEffect(id)
    local name = {
        "die_jiangshi", "die_nangua", "die_mutou", "die_guaishou", "die_shitou",
        "die_zhizhu", "die_fengheguai", "die_she", "", "die_xiezi",
        "", "", "", "", "die_munaiyi",
        "die_zipangxie", "die_shuiyuansu", "die_hongpangxie", "die_wenzi", "die_feiting",
        "die_laoshu", "die_shayu",
    }
    if name[id] ~= "" then
        local e = string.format("res/JunTuan/sound/%s.mp3", name[id])
        ViewBase:playEffect(e)
    end
end

-- 设置音效声音大小
function AudioManager:setVoiceVolume(value)
    ViewBase:setSoundVolume(value)
end

-- 预加载音效
function AudioManager:preloadEffect()
    for i, v in ipairs(self.effect) do
        cc.SimpleAudioEngine:getInstance():preloadEffect(v)
    end
end

-- 卸载音乐音效
function AudioManager:unLoadMusicAndEffect()
    for i, v in ipairs(self.effect) do
        cc.SimpleAudioEngine:getInstance():unloadEffect(v)
    end
end
-----------------------------------------------------

function AudioManager:isSound()
    local v = ViewBase:getSoundVolume()
    return v > 0
end

function AudioManager:isMusic()
    local v = ViewBase:getMusicVolume()
    return v > 0
end

function AudioManager:stopMusic()
    ViewBase:stopMusic()
end

return AudioManager