---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hkc.
--- DateTime: 2021/4/9 11:16
---

local Skill = class("Hero", cc.Node)

function Skill:ctor(SkillInfo)
    self:enableNodeEvents()
    self:initData(SkillInfo)
end

function Skill:initData(SkillInfo)
    self.damage = SkillInfo.damage
    self.critRate = SkillInfo.critRate

end

function Skill:onEnter()

end

function Skill:onExit()

end

return Skill