require("src.config")
require("src.functions")
require("src.ChannelVersion")
require("src.debugConfig")
require("src.cocos.init")
require("src.app.NetConfig")

require("src.config.GameConfig")
require("src.config.TipCfg")
require("src.protobuf.header")
require("src.Define")

require("src.app.Component.ViewBase")
require("src.app.Component.DialogManager")
require("src.app.Component.ClippingNodeUtils")

require("src.app.Manager.UpdateManager")
require("src.app.Manager.HttpManager")
require("src.app.Manager.MessageManager")
require("src.app.Manager.SceneManager")
require("src.app.Manager.LoginManager")
require("src.app.Manager.GameManager")
require("src.app.Manager.ChatManager")
require("src.app.Manager.Net.GameNetManager")
require("src.app.Manager.Net.ChatNetManager")

require("src.Util.Base64Util")
require("src.Util.CodeUtil")
require("src.Util.HttpUtil")
require("src.Util.CommonUtil")
require("src.Util.DeviceUtil")
require("src.Util.ThirdUtil")
require("src.Util.WebViewUtil")
require("src.app.Model.UserData")
require("src.Util.SensorUtil")
require("src.Util.ScreenUtil")
require("src.Util.H5Pay")
require("src.Util.JsonUtil")
